// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn0Gf8xlQBrlur0jxdexl9ax1OauU0tvM',
    appId: '1:312704214017:web:c2ced683834721cb524c00',
    messagingSenderId: '312704214017',
    projectId: 'hallkaro',
    authDomain: 'hallkaro.firebaseapp.com',
    storageBucket: 'hallkaro.firebasestorage.app',
    measurementId: 'G-YFNDP5Q1D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAecAglJJ-eH6WjQdjRfSBHvMjt0AL4deU',
    appId: '1:312704214017:android:3c52751aa0cd7cdb524c00',
    messagingSenderId: '312704214017',
    projectId: 'hallkaro',
    storageBucket: 'hallkaro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByGqX7Bj7zh9tP9ORKuJ8UNG1D1aswbKo',
    appId: '1:312704214017:ios:446e3b26df6e86df524c00',
    messagingSenderId: '312704214017',
    projectId: 'hallkaro',
    storageBucket: 'hallkaro.firebasestorage.app',
    iosBundleId: 'com.example.hallKaro',
  );
}
